<?php 
	echo $this->getContent(); 
?>

<h2>States</h2>

<?php
	foreach($countries as $singleCountry){
		echo "<div>";
		echo $singleCountry->Id." ".$singleCountry->Code." ".$singleCountry->Name;
		echo " ".$this->tag->linkTo(array('admin/reference/country/'.$singleCountry->Id, 'Edit', 'class' => ''));
		echo " ".$this->tag->linkTo(array('admin/reference/country/'.$singleCountry->Id, 'Delete', 'class' => ''));
		echo "</div>";
	}
?>

<h2>Create Country</h2>

<?php echo $this->tag->formFor("admin/reference/country"); ?>
	<div class="form-group">
		<label for="Code" class="col-sm-2 control-label">Code</label>
		<div class="col-sm-2">
			<?php echo $this->tag->textFieldFor(array("Code", "value"=>$country->Code)) ?>
		</div>
	</div>

	<div class="form-group">
		<label for="Name" class="col-sm-2 control-label">Name</label>
		<div class="col-sm-5">
			<?php echo $this->tag->textFieldFor(array("Name", "value"=>$country->Name)) ?>
		</div>
	</div>

	<div class="form-group">
		<div class="col-sm-offset-2 col-sm-10">
			<?= $this->tag->submitButton(array("Submit", 'class' => 'btn btn-default')); ?>
	    </div>
	</div>
</form>