<?php use Phalcon\Tag as Tag ?>
<!DOCTYPE html>
<html lang="en">
    <head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<?php 
        	echo Tag::getTitle();
        	$this->assets->outputCss('cssMain');
        ?>
        
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="">
        <meta name="author" content="Copyright © 2014. Eryco Putra">
    </head>
    <body>
		<div class="container">
        	<h1>Site Master</h1>

        	<?php echo $this->getContent() ?>
        	
        	<div class="footer"><?php include "partials/footer.php" ?></div>
		</div>
		
		<script type="text/javascript">
			var baseUrl = '<?php echo $this->url->get("") ?>';
		</script>
		
		<?php 
			$this->assets->outputJs('jsMain'); 
			echo empty($jsViewBuilder) ? "" : $jsViewBuilder;
		?>
    </body>
</html>